### ISSUE TITLE
try/catch form on the right hand of a rule causes NPE when compiling the rule

### ISSUE THREAD

**Issue by leifwalsh** [rbrush/clara-rules#104]
I was writing a rule to verify that an input string can be parsed as an integer, so I wrote something like this:

```clj
(defrule key-is-number
  [KVPair (= ?id id) (= ?num-str (second (re-find #"^/path/to/integer/([^/]+)" key)))]
  [: test (not (nil? ?num-str))]
  =>
  (try
    (Integer/parseInt ?num-str)
    (catch NumberFormatException _
      (insert! (->Error ?id :type-error (str ?num-str " must be a number."))))))
```

When trying to load this rule, I got a NumberFormatException from the compiler that looked something like this:

```
2. Unhandled clojure.lang.Compiler$CompilerException
   Error compiling:
   foo.clj:115:15

...

1. Caused by java.lang.NullPointerException
   (No message)

        ConcurrentHashMap.java:  333  java.util.concurrent.ConcurrentHashMap/hash
        ConcurrentHashMap.java:  988  java.util.concurrent.ConcurrentHashMap/get
                Namespace.java:  188  clojure.lang.Namespace/find
                      core.clj: 3798  clojure.core/find-ns
                      core.clj: 3830  clojure.core/the-ns
                      core.clj: 3837  clojure.core/ns-name
                       dsl.clj:  137  clara.rules.dsl/maybe-qualify
                       dsl.clj:  158  clara.rules.dsl/resolve-vars/fn
```

Converting this rule to something like this succeeds, so it seems like it's the try/catch block that's to blame.  Maybe Clara is trying to find the symbol try?

```clj
(defn is-num?
  [s]
  (try
    (Integer/parseInt s)
    true
    (catch NumberFormatException _
      false)))

(defrule key-is-number
  [KVPair (= ?id id) (= ?num-str (second (re-find #"^/path/to/integer/([^/]+)" key)))]
  [:test (not (nil? ?num-str))]
  =>
  (when-not (is-num? ?num-str)
    (insert! (->Error ?id :type-error (str ?num-str " must be a number.")))))
```

**Comment by rbrush** [comment]
Thanks for reporting this. It does look like Clara is tripping on the special symbols int he try/catch syntax. The good news is the fix should be straightforward. I'm not able to jump in right now, but I should be able to get this fixed in the next day or two.

**Comment by leifwalsh** [comment]
No rush, the workaround works fine. Thanks for the fast diagnosis!



-- 
Cheers,
Leif

**Comment by mrrodriguez** [comment]
I actually think Clara is failing to parse the Integer/parseInt form correctly. I have ran into w similar situation before. 

From a parsing perspective This is a trickier case since the symbol appears to be a namespace qualified symbol given the "/". However this is just a special cased sort of macro that expands to a "." (Dot) special form in the clj compiler.

**Comment by rbrush** [comment]
This should be fixed in the above commit. I'll leave this issue open for the time being in case there is something I'm missing, but I'll plan to include it in an 0.8.7 release soon.

**Comment by mrrodriguez** [comment]
It looks like I was off-base with my first assumption of what doesn't work here.

However, I am still thinking it would be a good improvement to actually qualify class name symbols that are used in the RHS (and wherever else it applies to).  The namespace the rule is defined in may have `import`s on class names. 

So you could have a rule like
```clj
(inport 'java.util.ArrayList)

(defrule find-array-list
  [?x <- Object]
  =>
  (if (instance? ArrayList ?x) (insert! :found-it) (insert! :did-not-find-it)))
```
I'll admit that is a bad example.

Also, I'd think that static method calls should be qualified, so things like:
```clj
(import 'java.io.File)

;;; some RHS
(File/listRoots)
```

Either way, these aren't critical suggestions, I just think it could lead to a subtle issue if a rule was parsed in one namespace with imports and then attempted to be compiled/resolved in a different namespace lacking these imports.

**Comment by rbrush** [comment]
Good points, Mike. I went ahead and added a commit that qualifies static method calls and class names to avoid these issues in the future.

**Comment by mrrodriguez** [comment]
That looks good. Thanks for the quick enhancement on this!

**Comment by rbrush** [comment]
Closing this for the 0.8.7 release

**Comment by leifwalsh** [comment]
Thanks everyone!



-- 
Cheers,
Leif
