### ISSUE TITLE
Any plan for a 0.8.8 release?

### ISSUE THREAD

**Issue by francoisroyer** [rbrush/clara-rules#112]
This to benefit from a recent release of Prismatic Schema (>= 0.4), since clara 0.8.7 depends on deprecated features (namely sm/defn).
Thanks!

**Comment by rbrush** [comment]
Sure, I'll get a release pushed out, probably tomorrow, using Schema 0.4.3. We've been focused on projects using Clara (and the move to Clojure 1.7 reader expressions) but a 0.8.8 release is simple enough to do.

**Comment by francoisroyer** [comment]
Thank you a thousand times !

**Comment by rbrush** [comment]
Haha, you are most welcome! I'll post back on this issue when the release is out.

**Comment by francoisroyer** [comment]
Thank you - tomorrow would be awesome, we wouldn't have to package 0.8.8-SNAPSHOT in our jars for jenkins

**Comment by rbrush** [comment]
And 0.8.8 has been released and is available on clojars! It includes a couple small bug fixes over 0.8.7 and Prismatic 4.3. Details here: https://groups.google.com/forum/#!topic/clara-rules/VEy0GhwoEFM

Let me know if you have any problems with the released artifact.

**Comment by rbrush** [comment]
Cleaning this up. 0.8.8 was released a while ago, so there's nothing left to do here.
