### ISSUE TITLE
retract-facts-logical! listener not being called

### ISSUE THREAD

**Issue by jpthomson** [rbrush/clara-rules#117]
I'm using a custom listener to dispatch notifications and noticed that my `retract-facts-logical!` listener wasn't being called. A quick github search suggests the call is missing:

https://github.com/rbrush/clara-rules/search?utf8=%E2%9C%93&q=retract-facts-logical%21

Is this an easy fix or is there some complexity in supporting it?

-Jonathan

**Comment by rbrush** [comment]
Looks like an oversight. I'll get this call added to the retraction flow in clara.rules.engine.ProductionNode so it shows up.

**Comment by rbrush** [comment]
It should be fixed in the above commit. Let me know if this isn't working as you'd expect.

**Comment by jpthomson** [comment]
Works great, thanks Ryan!

**Comment by rbrush** [comment]
Closing since this was fixed and marking for the 0.8.9 release.
