### ISSUE TITLE
Binding record extmap fields

### ISSUE THREAD

**Issue by devn** [rbrush/clara-rules#123]
Would it be possible to expand list of symbols that are bindable to include keys found in `__extmap` on a record?

```clojure
;; Define a record with only the field 'a' defined
(defrecord Foo [a])

(let [r (map->Foo {:a 1 :b 2})]
  (:b (.-__extmap r))

;; => 2
```

I realize there are likely some performance-related implications to doing this, and wanted to get your feedback before submitting a PR.

Thanks for all of your great work.

**Comment by rbrush** [comment]
Hi Devin,

I always viewed __extmap as an private implementation detail and avoided exposing it to users. If you do need to access items that aren't defined in your record, you can destructure within the rule itself using the standard Clojure restructuring mechanism. So this should work as you'd expect:

```clj
(defrecord Foo [a])

(defrule print-b
  [Foo [{:keys [a b]}] (= ?b b)]
  =>
  (println ?b))
```

Hopefully this meets your needs! If not we can look for some alternative.

-Ryan

**Comment by devn** [comment]
Hi Ryan,

Thanks a lot for the reply; that's exactly what I was after.

On a quasi-related note, I have been working to model an existing codebase in Clara and what I've done so far is insert a record of a new type on the `rhs` for every rule in the system. What I mean is, I've been doing something like this:

```clojure
(defrecord Qux [a])
(defrecord Foo [a b])
(defrecord Bar [a b c])

(defrule ...
  [Qux (= ?a a)]
  =>
  (insert! (map->Foo {:a ?a :b 42}))

(defrule ...
  [Foo (= ?a a) (= ?b b) (= ?c c)]
  =>
  (insert! (map->Bar {:a ?a :b ?b ?c 142}))
```

Assume in the above example that `Qux`, `Foo`, and `Bar` are basically all the same type of fact: `FooBarQux`. What I'm trying to understand is whether or not it's okay to `assoc` additional data onto the record in the `rhs`, or if I should always prefer to create a new record with named fields? I am starting to amass quite a collection of record types which are noun-laden, and I'm wondering if it's reasonable to "decorate" facts in this way.

I may be explaining this rather poorly, so please feel free to ask questions if I'm missing something obvious. This is my first foray into expert systems, and any guidance is much appreciated.

Thanks,
Devin

**Comment by devn** [comment]
This _might_ be a more concrete example:

`Patient` was defined with `gender` and `age` in the original record. Given a number of factors, the `Patient` may have some intermediate information added to it: `{:likes :pizza}`. Does this mean I should create a separate fact for `PatientLikesPizza` with the field specified, or is it alright to go ahead and tack `:likes :pizza` onto the existing `Patient` by dropping it into `:__extmap` and destructring in the `lhs`? The explosion of facts makes me feel like I'm thinking about this wrong.

**Comment by rbrush** [comment]
One alternative is to explicitly have a field in the record for your
extensions. Something like:

(defrecord Patient [gender age extensions])

And put your additional data in there, e.g. (map->Patient {:gender :female
:age 65 :extensions {:likes :pizza})

If you don't want to add an explicit extensions field, you could get access
to the record itself with the :as type of restructuring, like this (note I
didn't test this code so I could have made a syntax error):

(defrule print-extensions
   (Person [{:keys [age gender] :as record}] (= ?likes-pizza (:likes-pizza
record))
   =>
   (println ?likes-pizza))

**Comment by devn** [comment]
*nod* That's a good idea, I just didn't know if paying the map lookup cost would be expensive, but I suppose at that point I could just make a `PersonExtensions` record and either pass or create it in the `rhs`.

Thanks for all of your help, Ryan. It is much appreciated.

Cheers,
Devin
