### ISSUE TITLE
Merge Clojure and ClojureScript user-facing macros

### ISSUE THREAD

**Issue by rbrush** [rbrush/clara-rules#128]
This issue is to track the good idea mentioned by @stephenbrady in issue #110. I copied it here for convenience:

I appreciate all the hard work being done here. I'm not quite sure I've seen all the places where this refactoring is happening, but I'll bring this up just in case. I'd suggest taking this opportunity to consolidate the api between clj and cljs further so that a :require-macros [clara.macros :refer [defsession defrule defquery]] isn't necessary for cljc/cljs usage (and the attendant reader conditionals that are necessary around those parts of the ns declaration when using clara within a .cljc file).

Prismatic Schema is an example of this where they (effectively) do a #?(:cljs (:require-macros schema.core).

https://github.com/prismatic/schema/blob/master/src%2Fcljx%2Fschema%2Fcore.cljx#L88

The defsession, defrule, and defquery macros would need to be compile environment aware, but I see that's already happening elsewhere here: https://github.com/rbrush/clara-rules/blob/master/src%2Fmain%2Fclojure%2Fclara%2Frules%2Fcompiler.clj#L49

We have many rules that are shared between clj and cljs in .cljc files, so this change would really clean up our ns declarations. I'd submit a PR, but it seems like there's a lot of code in motion right now.

**Comment by rbrush** [comment]
Took a stab at this in the above commit. ClojureScript users can now refer to the defrule, defquery, and defsession macros in the clara.rules namespace, which just defers the logic to the clara.macros. We keep the existing items around to support existing code, but may move it in a future release.

**Comment by rbrush** [comment]
Merged into master.

**Comment by stephenbrady** [comment]
Great - thanks! Looking forward to the next release.

**Comment by rbrush** [comment]
FYI @stephenbrady, clara-rules 0.9.0 is up on Clojars and contains this enhancement.

We will probably simplify this code in the future, since ClojureScript has better support for working with vars than it did when I wrote this originally. I'm tracking this in issue #140.

**Comment by stephenbrady** [comment]
Thanks for the heads up! First pass, no problems with 0.9.0 in our code base.

**Comment by stephenbrady** [comment]
@rbrush Following up on this as we've now had a chance to actually start using the reorganized clara 0.9.0, you can go one further with my suggestion and do a `require-macros` in `rules.cljc` like so:
```
(ns clara.rules
  (:require [ ... ])
  #?(:cljs (:require-macros clara.rules)))
```
As a consumer of the `clara.rules` namespace from my .cljc file, my `ns` decl would look like this:

```
(ns my.app
  (:require [clara.rules :as clara]))

(clara/defrule ...)
```

That would allow the clara user to avoid reader conditionals entirely, and it would not be necessary to even do what is suggested here: https://github.com/rbrush/clara-rules/blob/master/src%2Fmain%2Fclojure%2Fclara%2Fmacros.clj#L7-L8

**Comment by rbrush** [comment]
Sounds reasonable to me. Will the commit linked below do the trick? All of my tests run fine with this change, although I typically explicitly refer to the Clara macros directly just as a style preference.

https://github.com/rbrush/clara-rules/commit/956cbb86f13dd7c8a52014771e8ef743b76b1ba5

I mostly use the Clojure version of Clara in production so I appreciate the feedback on improving the ClojureScript use case. 

-Ryan

**Comment by stephenbrady** [comment]
Yes perfect. Thanks!

Well, one isn't precluded from doing a :require-macros with this change. As a point of reference for this practice: https://github.com/prismatic/schema/blob/master/src%2Fcljx%2Fschema%2Fcore.cljx#L88
