### ISSUE TITLE
Add exists operator

### ISSUE THREAD

**Issue by rbrush** [rbrush/clara-rules#130]
Add an :exists operator that can be used in addition to :and, :or, and :not. Discussion of the desired behavior is on the mailing list here:

https://groups.google.com/forum/?hl=en#!topic/clara-rules/PXY2nU3ZyYc

**Comment by rbrush** [comment]
An initial pass at an implementation is in the above commit. I took the approach of simply expanding an exists expression into a counting accumulator and a test, which is probably the simplest way to support this functionality.

There may be some small performance gains that could be created with a specialized ExistsNode, but it doesn't seem like that would be significant for most workloads. So I think the current strategy is sufficient to add support, and we can reserve the write to adopt a specialized node later.

**Comment by mrrodriguez** [comment]
+1
I think it will be useful to have.  I think that is a good idea to just keep the implementation simple like this for now with the flexibility to change it if needed later on.

**Comment by rbrush** [comment]
Merged. Thanks for the feedback!
