### ISSUE TITLE
Docs: Minor documentation issue with new clara-rule.org

### ISSUE THREAD

**Issue by kahunamoore** [rbrush/clara-rules#136]
Given that it is highly visible on the home page I thought you'd want to know. In the "Easily used from Java" section it reads:

"Just include your rules as a resource in your and use Java Beans or Clojure records as facts."

I suspect you wanted to say something between "in your" and "and use Java Beans..".

**Comment by rbrush** [comment]
Fixed. Thanks for letting me know!
