### ISSUE TITLE
Cannot use the Java API from Java 7

### ISSUE THREAD

**Issue by tothda** [rbrush/clara-rules#146]
Hi! We are using the latest version ("0.9.1") from Clojars, but we can't call it from Java 7. The class files in clara-rules-0.9.1.jar seem to be compiled only for Java 8.

![screenshot from 2015-12-08 16 43 23](https://cloud.githubusercontent.com/assets/7077/11659975/23388204-9dcb-11e5-9ebf-af6902104348.png)

As a workaround we recompiled it with Java 7, and it works now.
It would be nice to recompile the artifact with the -target 1.7 flag (or lower if possible).

p.s. Thanks for this great library!

**Comment by rbrush** [comment]
Ah, my mistake. Fortunately it's a simple fix and I'm planning on releasing clara-0.9.2 in the next few days for unrelated reasons anyway. I will target the Java classes to 1.6. (You'll need Java 1.7 or newer to use the ClojureScript version, but this may not apply to you.)

Thanks for reporting this!

**Comment by tothda** [comment]
Awesome. Thanks for the quick fix.

**Comment by rbrush** [comment]
Targeting this for 0.9.2 and closing since there isn't anything more to do here. This will be released this week.

If other problems arise we can reopen or log a new issue.
