### ISSUE TITLE
Binding and equality sugar

### ISSUE THREAD

**Issue by devn** [rbrush/clara-rules#150]
Discussed briefly on the #clara channel in the Clojurians slack.

It would be nice to have a way to both bind and check for equality without separate statements.

For instance, in Drools you can do the following:
`Cheese( $chedddar : name == "cheddar" )``

Right now, I wind up doing a fair amount of:
`[Foo (= ?x x) (= x "bar")]`

This can get a little bit more verbose than I'd prefer in situations where more than a few fields are bound and have an equality check.

It might be nice to have some sugar for this. Here's a guess at one way you might represent it.
`[Foo (== {?x x} "bar")]`
where `?x` is bound to the value of `x`, and an equality check happens against `"bar"`. `==` keeps it separate from `=`, and enforces that the first element in the form must be a map of a `?`-prefixed symbol to any valid symbol.

**Comment by rbrush** [comment]
Would supporting further arities in equal expressions work? Perhaps something like:

```clj
[Foo (= ?x x "bar")]
``` 

I think the semantics of this would be intuitive for anyone who knows Clojure and keeps the number of specialized forms small.

**Comment by devn** [comment]
:+1: That'd be great.

**Comment by rbrush** [comment]
The above commit  now supports binding things like ```[Foo (= ?x x "bar")]``` or even ```[Foo (= ?x ?y x "bar")]``` with what I think is the most intuitive behavior. Basically, one or more variables can be bound in an expression, and it also ensures equality checks for other values are performed.

I'll merge this into master shortly unless there is any feedback on the approach.

**Comment by rbrush** [comment]
Above commit erroneously referenced this issue. But it is fixed here: https://github.com/rbrush/clara-rules/commit/4a3c9b1c8fe09f47383ab3e651aebf4faefb0f6f.

I don't think there is anything more to do with this one so I'm going to close it and target for 0.9.3. We can reopen or create a new issue if you disagree.

**Comment by rbrush** [comment]
The next release will probably be 0.10.0. Updating the milestone to reflect that.
