### ISSUE TITLE
Binding and equality documentation, example documentation updates

### ISSUE THREAD

**Issue by devn** [rbrush/clara-rules#151]
There are a few places where `==` is still being used in the examples, but as far as I know, there is no description of the difference between `==` and `=`. My understanding is there is no difference, and `==` is no longer needed. If this is the case, then references to `==` should be replaced with `=` in project documentation and examples.

In addition, it would be nice if there was a bit of documentation on `=`. `(= 2 ?bar bar)` is not the same as `(= ?bar bar 2)`, for instance.

**Comment by rbrush** [comment]
The presence of == remains from an early requirement for this. Agreed it should be removed.

The current behavior of multiple arity equals (= 2 ?bar bar) is probably an accident of the implementation. The Least Surprising Behavior for this should be to unify all Clara variables and do a an equality check for other items. Would changing that help here and also fix #150 as well?

**Comment by devn** [comment]
Yes, I believe it would.

**Comment by mrrodriguez** [comment]
+1 to not having `==` anymore in docs.  I've seen people confused on that a little before.

**Comment by rbrush** [comment]
I went ahead and remove == from the clara-examples project in this commit: https://github.com/rbrush/clara-examples/commit/f7bda7e8c676eb6a3d3a4f93ccf57770d2994906

There remains some in clara-rules but I'll remove those as well after merging some other changes.

**Comment by rbrush** [comment]
I think this is fixed. clara-examples is updated and I removed the confusing behavior around equality binding with the fix for issue #150. Is there anything else we should include in this issue?

**Comment by devn** [comment]
I believe anything else would be out of scope, so unless there's any objection I'd suggest this be closed.

**Comment by rbrush** [comment]
Closing and targeted at 0.9.3. Thanks!
