### ISSUE TITLE
Suggestion to improve efficiency.

### ISSUE THREAD

**Issue by ylando2** [rbrush/clara-rules#17]
You use hash to create id, I think that you can improve the efficiency of the rolebase system by creating an id serially 0..N and use a map node to id for the optimizations. Using a serial id can help improve the memory efficiency because you can put all the memory in vectors instead of maps.

**Comment by rbrush** [comment]
The code has been refactored and optimized significantly since this, including as how described in the comment above. I'm going to go ahead and close since so many optimizations have applied over the last several months. We can open new issues if other opportunities emerge.
