### ISSUE TITLE
Incorrect rule activation for complex nested negations with insert-unconditional

### ISSUE THREAD

**Issue by WilliamParker** [rbrush/clara-rules#174]
I'd expect the following test to pass:

````
(deftest test-complex-nested-truth-maintenance-with-unconditional-insert
  (let [r (dsl/parse-rule [[Cold (= ?t temperature)]
                           [:not [:or [ColdAndWindy (= ?t temperature)]
                                  [Hot (= ?t temperature)]]]]
                          (insert-unconditional! (->First)))
        q (dsl/parse-query [] [[First]])

        empty-session (mk-session [r q])]
    (is (= (-> empty-session
               (insert (->Cold 10) (->Hot 10))
               (fire-rules)
               (query q))
           []))))
````

Instead, it fails:

````
expected: ({})
  actual: []

expected: nil to be an instance of clojure.lang.PersistentVector
     was: nil is an instance of nil
       nil
````

However, if I change insert-unconditional! to insert! it passes.  I believe the root cause
of the failure here is that [1] propagates the exact salience from the original rule to the extracted negation rule.  Thus, the remainder of the original rule (without the extracted negation condition) can fire even if the extracted rule fires as well.  When using truth maintenance, any facts
inserted by the original rule should be retracted in the end, but if the salience ordering
is such that the negation condition should match something before the rule in question fires
at all it seems that Clara should prevent that RHS from ever firing.  Having ordering guarantees
like this change based on the type of constraint seems undesirable.

This can be fixed by assigning the extracted rule a higher salience than the original rule.
However, it shouldn't take on a salience that prioritizes it above another rule provided by the user
that has higher salience than the original rule.  That is, if we had a rule R1 with salience 1 and R2 with salience 2 we wouldn't want a rule extracted from R1 to have salience greater than 2.  The compiler might be able to use some spacing strategy to guarantee this, but I believe the simplest way to accomplish this would be to use an activation-group-sort-fn [2] that sorts first based on the user-provided salience (as defined by the user-provided sorter) and then based on an internal Clara parameter.  The internal Clara salience would only be considered if the user-provided function considered two rules to have equal salience.  The compiler would turn salience into tuples like [user-salience internal-salience].  So, for example, in the case before, we'd have

R1 salience: [1 :default]

R1 extracted rule salience: [1 :extracted-negation-rule]

R2 salience: [2 :default]

To be clear, the user wouldn't see any of this; user-written rules would still provide salience
in the same way as currently.  The sorting function would, after wrapping, consider the first element of the tuple (the user-provided salience) first and then use the second element as a tiebreaker using an ordering defined in the compiler.  This would also have the benefit of being easily extensible to any other rule extraction the compiler might do in the future.

Thoughts?

1. https://github.com/rbrush/clara-rules/blob/0.10/src/main/clojure/clara/rules/compiler.clj#L899
2. https://github.com/rbrush/clara-rules/blob/0.10/src/main/clojure/clara/rules/compiler.clj#L1483

**Comment by rbrush** [comment]
Would there be any visible, negative impact if the extracted negation is fired before another user rule? Since the inserted NegationResult fact uses truth maintenance, it seems like this shouldn't have any visible impact and we could just increment the salience by 1. This seems like the simpler fix (although it does seem a bit arbitrary and hack-ish).

However, I still think your proposal has merit. The internal, secondary salience you suggest could be useful for other things as well. For instance, I think Drools attaches an implied salience to rules based on the order they appear in a file. We could do the same by having a [user-salience internal-salience] tuple. So I'd support going down that route if it seems worthwhile.

**Comment by WilliamParker** [comment]
I think you're correct that making the ordering be "incorrect" in that way wouldn't actually
produce incorrect outcomes, assuming that additional rules don't use the fact type
that the extracted rule inserts and that the LHS code is pure (both of which should be true).
I believe the only impact would be on performance; Clara would effectively be creating an ordering
different from that provided by the user in some cases, which could potentially perform worse than the user-provided ordering.  This would happen if you had a sequence of events like this:

R1 = rule with salience 1
R2 = rule with salience 2

1. Extracted rule from R1 fires.
2. R2 fires, inserting something invalidates the above insertion.
3. Step 1 is retracted.

In the simple case this is trivial, but in principle I think you could create some
pathological scenarios.  For example, the extracted negation condition could have an accumulator
that would be forced to repeatedly reevaluate.  That likely falls well into edge case territory
though and might not be worth worrying about until/unless such a use case comes up.

However, there is also another problem that just occurred to me this morning.  I mentioned spacing logic - that is, choosing a numerical salience less than the next greatest salience - as a possible solution before.  So for example, if we had rules with salience with 1, 1.5, and 2, and we needed to extract a negation condition from the rule with salience 1.5, the Clara compiler would choose a value greater than 1.5 but less than 2 for the auto-generated rule.  I don't think that is actually possible in general.  If the user provides a custom activation-group-sort-fn [1] it is possible that the salience may not even be numeric.  Since that comparison function is a black box as far as Clara is concerned, I don't see a way that Clara can "add" to that salience in general.  This is also a problem for the approach of just adding some arbitrary number to the salience of the extracted negation rule to which I see no solution.

Another issue here that @mrrodriguez pointed out to me is that currently the salience used for sorting is actually generated by the activation-group-fn each time an activation is added to the memory. [2, 3]  Thus, as the memory is written now the "internal" salience would need to be retrieved separately
rather than just folded into a new salience comparison function on tuples.  I believe this would be relatively easy to change though; since the salience is pulled from the production it would be valid to just compute the salience for each production in the compiler and have the memory just look up a key rather than call a function every time.  That seems like a cleaner way to generate the salience anyway to me and would probably perform slightly better since it would eliminate repeated calls to that function during rules execution (although the default is a cheap function so in the default case it probably doesn't matter much perf-wise).

I do see a disadvantage to the multi-level salience approach though in that the activation sorting would become more expensive.  My guess is it wouldn't be by much if it was done carefully, but it would be something to be mindful of.  On the other hand, eliminating per-activation calls to the activation-group-fn might end up being a net perf gain (although probably a tiny one).

Regarding ordering based on positions in a file, that is something we've been thinking about as well.  We're looking at moving some rules we currently have in Drools to Clara, and the fact that Clara doesn't order based on position and Drools does presents potential performance problems, but in our testing so far Clara has been faster anyway.  Such ordering might make Clara even faster though or more resilient to problematic data scenarios.


1. https://github.com/rbrush/clara-rules/blob/0.10/src/main/clojure/clara/rules/compiler.clj#L1483
2. https://github.com/rbrush/clara-rules/blob/master/src/main/clojure/clara/rules/memory.cljc#L331
3. https://github.com/rbrush/clara-rules/blob/0.10/src/main/clojure/clara/rules/compiler.clj#L1487

**Comment by rbrush** [comment]
Alright, you've convinced me that some form of internal salience invisible to the user that is used as a tiebreaker is the way to go. (I'm not worried about the performance cost of activation sorting...that will almost certainly be negligible when compared to the activations themselves.)

I haven't thought much about the mechanics of how we'd introduce this, but I'd be happy to make this change myself. However, if you're looking at it and were interested and able to take a pass, then please feel free to do so.

**Comment by WilliamParker** [comment]
I can take care of this sometime over the next week or two.  I don't actually think it should take too long; I've sketched out the implementation already.  Thanks for your responsiveness to issues on this project!

**Comment by rbrush** [comment]
Sounds great, Will, and thanks! 

Let me know if you want to kick around a strategy for this, or if something comes up and you aren't able to jump into it soon. (Translation: I wrote this bug and while I'm happy to accept contributions to fix it, I don't want you to feel obligated to do so.)

**Comment by WilliamParker** [comment]
I have an initial draft of this at https://github.com/WilliamParker/clara-rules/commit/871c77d368dd9bc9b502ceec93cb96947e981ef7

Overview:

The activation-group-fn now produces a tuple of [rule-salience internal-salience] and that tuple is what is then compared in the activation map, using the rule-salience first.  I added testing for various combinations of different manual and default activation-group-fn and activation-group-sort-fns to validate that this doesn't break existing functionality.  Everything passed on https://travis-ci.org/WilliamParker/clara-rules/builds/114818074

There is part of this that I wanted to ask about.  I see that assemble-session at [1] pretty much duplicates the functionality in the compiler for creating these functions [2].  I could just copy the new functions over to assemble-session as well, but I wonder if the better solution would be to put them someplace common in a .cljc file.

Other notes:  I was initially going to move the salience into a field on the ProductionNode so that it wouldn't need to be recalculated but it looks like that may be a bit tricky due to the need to support ClojureScript session creation and I think some compiler function signatures might need to change.  It would probably be achievable, but I think I agree that it wouldn't be a likely hotspot and I actually profiled something fairly similar in our codebase recently and the cost wasn't noticeable.  I thought that part would be a very easy enhancement, but I think I was mistaken on that point.  I also switched the functions in the session options (salience functions, alphas-fn, and the ancestors-fn) to be like

````
(or (get options :keyword)
      default-fn)
````

instead of 

````
(get options :keyword default)
````

The difference here is that the "or" version will use the default if you give an explicit nil value.  Nil will just blow up with an NPE, so I don't see a valid use-case for wanting to actually use it, and when creating sessions with arguments constructed dynamically it seems easier/more consistent with Clojure conventions to me to allow a nil value under the key than requiring the caller to remove the key.

Also, I looked at the way comparisons are done in Clojure [4] and ClojureScript [5], and it looks like it is the same, so I think the same activation-group-sort-fn logic can just be reused for both.  (As opposed to needing to write different Clojure and Clojurescript functions).

1. https://github.com/rbrush/clara-rules/blob/0.10/src/main/clojure/clara/rules.cljc#L221
2. https://github.com/rbrush/clara-rules/blob/0.10/src/main/clojure/clara/rules/compiler.clj#L1475
3. https://github.com/rbrush/clara-rules/blob/0.10/src/main/clojure/clara/rules/memory.cljc#L297
4. https://github.com/clojure/clojure/blob/clojure-1.7.0/src/jvm/clojure/lang/AFunction.java#L46
5.https://github.com/clojure/clojurescript/blob/f58dcdf4dc37ef52d4eb1e2b7c994282bf6351f5/src/main/cljs/cljs/core.cljs#L2171

**Comment by rbrush** [comment]
Great! The overall approach looks good. 

As for the redundancy around assemble-session, I think it does make sense to refactor the common parts now that it's getting more complicated. The ClojureScript code can't depend on anything from clara.rules.compiler, but we could add something like a ```rulebase-and-options-to-session``` function in clara.rules.engine that does as much common work as possible, including all of the logic around activation sorting.

Some logic -- I think most things up to creating the rulebase itself -- will need to be separate in the Clojure and ClojureScript worlds to work around ClojureScript's lack of eval. But the salience functions should be able to move. clara.rules.engine is a good place to put this since it's common between the platforms and does not need anything that uses eval.

Thanks for working on this!

**Comment by WilliamParker** [comment]
I have created a pull request for this at https://github.com/rbrush/clara-rules/pull/176

I moved the activation group and activation group sort function generators into the engine;
they take the session options as a parameter and return the function that should be used.
The same functions are called in compiler/mk-session* and rules/assemble-session, which should limit
the ability for those to diverge. Regarding the ClojureScript side, I see that according to this comment [1] salience is not supported in the ClojureScript version.  I don't see a reason for this to be the case; is this no longer accurate or am I missing something?  If there is salience in the ClojureScript version now
I can add a test in test_rules.cljs if desired; the current overall pattern appears to me to rely primarily on the Clojure tests (which have the benefit of allowing dynamic creation of sessions to test scenarios).

Regarding the salience comparison function, there is a small user-facing behavior change.  When Clojure uses a function as a comparator, it expects the return value to be either a boolean or a number. [2]  ClojureScript (at least sorted-map-by), on the other hand, will use the number as a comparison value but otherwise falls back to Clojure(Script) truthiness semantics [3]. I considered using the comparator core function to get around this, as discussed in the comments on the previous draft, but the problem is that comparator just uses the truthiness semantics of Clojure(Script) while not using numerical return values [4, 5], so this would be a breaking change.  As written now, the only change is that Clojure Clara would use truthiness; all current valid cases would behave identically to before.  For example

````
(fn [a b] (if (some-condition a b) :truthy nil))
````
would currently blow up in Clojure but work in ClojureScript if used as the activation-group-sort-fn.  
After this change it would work in both.  I can change this to use reader conditionals, but I don't know
if replicating this behavior is worth the complexity or risk that Clojure might change (thus making Clara more strict than Clojure).  I don't have any idea at this time how likely such change would be.  This is probably a minor issue either way though.


1. https://github.com/rbrush/clara-rules/blob/0.10/src/main/clojure/clara/rules.cljc#L254
2. https://github.com/clojure/clojure/blob/clojure-1.8.0/src/jvm/clojure/lang/AFunction.java
3. https://github.com/clojure/clojurescript/blob/v1.8/src/main/cljs/cljs/core.cljs#L2115
4. https://github.com/clojure/clojure/blob/clojure-1.8.0/src/clj/clojure/core.clj#L2985
5. https://github.com/clojure/clojurescript/blob/v1.8/src/main/cljs/cljs/core.cljs#L9958

**Comment by rbrush** [comment]
This looks good to me. That ClojureScript comment may be out of date, but I think it's okay to move forward with the Clojure version and do the ClojureScript refactoring as a subsequent change, since it doesn't have nearly the usage of Clojure at this point. I'll plan on getting this merged today.

**Comment by rbrush** [comment]
The pull request has been merged, so I'm going to close this and target it at 0.11. We can log additional issues for any further changes.
