### ISSUE TITLE
Optimizing Clara local memory (JVM-side)

### ISSUE THREAD

**Issue by mrrodriguez** [rbrush/clara-rules#184]
## Background 

I have implemented a number of variations in clara.rules.memory to address performance concerns we've seen.  I'm going to give a fairly lengthy overview here in the hopes of getting some feedback from you on what I've done so far before I put out a concrete pull request on this issue.

----

In profiling, we have several cases where Clara's local memory model can get into execution time performance issues.  The culprit in many of these cases is the `clara.rules.memory/remove-first-of-each` function.  This function has come up as a performance hot spot in past issues as well, but a new approach is likely needed now to deal with some of the workloads we've seen in our scenarios.

Clara's local memory model is currently organized in a way that sort of extends on the concept of Clojure transient collection types.  Clara's memory to the consumer is immutable and persistent.  This is a great feature that allows for Clara sessions to be treated as any other immutable, persistent data structure.  However, Clara has a "transient" memory state where memory is made to be mutable.  This mutable memory is visibile and used only when many updates are happening on the same thread/call stack, which is invisible to the consumer.  This is currently implemented via a few mutable field instance variables on the memory `deftype`s along with the usage of Clojure transient collections on a few of the top-level local memory data structures.

The performance issue that has been observed is due to the local memory transient state using immutable, persistent Clojure collections to hold sequences of elements, tokens, activations, etc.  This means that any time `remove-first-of-each` is called, we are typically going to be completely rebuilding new immutable collections.  We need to remove arbitrary items from these immutable collections, so we do not even have an efficient way to attempt to remove an item out of the collection.  There are no simple "remove nth" functions for Clojure sequential types, like vectors or lists.  Just to note too, we primarily are dealing with lists here.  Profiling has revealed on many occasions that `remove-first-of-each` is spending a lot of time rebuilding these collections.

## Ideas

There are number of ideas of how to deal with this.  I'll try to briefly enumerate a few.

1) 
Idea:

Use something "indexed" on its items instead of sequential collections.  There are basically two options here, use sets or use maps.  Sets are not a good idea because we need to store facts that are equal to one another without losing the cardinality of those facts present in memory.  This leaves us with maps.  A map has the same issue as a set in that we cannot remove duplicates.  So it is natural to decide that a map should be keyed by items in memory with the value being the count of how many of those items remain in memory.  When the count reaches 0, the map entry can be removed entirely.  This is actually very similar to the approach taken with Drools (when dealing with logical insertions only, oddly enough; yet somewhat justified from their design perspective).

Pitfalls:

Facts in memory can be large.  They may also have inefficient hash codes.  There is really no guarantee that the items in memory make good and/or efficient keys in a hash map at all.  This can be a major problem in terms of efficiency of any approach to "indexing" based on arbitrary consumer-level facts given.  Tokens and activations can be even worse, since they are often aggregates over the facts in working memory.  We have used Drools extensively and have seen a lot of issues with some of our facts getting used by Drools as indexes into its working memory internal map structures.  Drools attempts to make this issue better, by wrapping facts with its own object type that caches the hash code of the underlying object in order to avoid recomputing it if it is not cached already by the given fact type.  However, this still ultimately leads to much more hashing needed than what Clara currently performs.  This would also be a significant overhaul in Clara to wrap all working memory elements with a wrapper type that was capable of caching hash codes like this, etc.

----

2) 
Idea: 

Be "more mutable" in the transient state of local memory.  Instead of using persistent, immutable collections to hold elements, tokens, activations, etc. use mutable collections that have efficient operations for removing arbitrary items from the middle of a sequence.  The type that stands out here is a linked list.  The removal will be linear since we have to find the item to remove, but removal operation itself is constant.  This is the approach I've began to lean towards at this point.

Pitfalls:

a) Mutable collections will have to come from the host platform.  So CLJ and CLJS implementations of clara.rules.memory will need to diverge more than they currently are.  In my current work with this, I have focused entirely on the JVM side and do not plan on optimizing the CLJS side right now.  The CLJS has been left with the original implementation and I will not discuss it more for the time being.
b) The persistent local memory returned to the caller, needs to really be persistent and immutable.  This means the transient memory mutable collections must be made persistent prior to returning.  This complicates the operations `to-transient` and `to-persistent!` of the local memory model.  

## Putting it in practice

I have invested time in the idea (2) from above.  I do not see (1) as a feasible approach at this point in time and I'm not even convinced it is valuable enough to be worthwhile.  The good news is that I've had success in profiling with this approach.  

We monitor the time it takes to run rule sessions against our datasets.  We log datasets as "long running" when the time it takes the rule session to insert all facts of our dataset and fire exceeds one minute.  One minute for us is significant and way over the average case per dataset.  Our average case is more like 200-800 milliseconds.  Obviously, when we see a dataset take one minute instead of 800 millisecond, it is time to investigate.

In Clara 0.11.1 several of the commits did bring down the number of "long running" datasets we have seen.  We had a few stubborn cases remaining that we have been trying to understand and find solutions to within the engine.  This has been a good testbed to find where Clara can still get significant performance improvements.

In a prototype using java.util.LinkedList instead of Clojure persistent, immutable collections, I found that all of our "long running" datasets were resolved.  We still have cases where more time is being spent than desirable (less extreme outliers from the average), but eliminating the above one minute case is still significant.  This led me to have confidence that memory really does need an overhaul when it comes to efficient removal of elements, tokens, activations, etc which is common during insertion and the fire rules loop.

## Concerns

I feel pretty good about the changes I've made in that they optimize the `remove-first-of-each` path that has came up in profiling as a bottleneck on a number of occasions.  The negative side to this is that this is JVM specific, so would have to be replicated separated for CLJS if the need came up from other consumers.  I suspect these larger dataset situations will continue to be more common the JVM side, than the JS side though.  Another negative is that this does add additional complexity to the local memory implementation.  However, this is often the case with optimizations, so that isn't really a surprise.

The most alarming part of this change is that it can actually cause a significant degradation of performance in a workflow that was making heavy use of `to-transient` and `to-persistent!` of local memory.

An example being something like:
```clj
(reduce (fn [s items] (fire-rules (insert-all s items))) (mk-session rules) [[item1 item2 item3] [item4 item5]])

```

Every time `insert`, `insert-all`, `retract`, `fire-rules`, etc return to the caller, the memory has to be made persistent again via `to-persistent!`.  When memory changes are happening, we have to make memory transient again via `to-transient`.  The simplest approach is to just eagerly convert all persistent, immutable collections to Java mutable collections when calling `to-transient` and then back to immutable collections when calling `to-persistent!` and this is what I did initially.  In our workflow, it doesn't necessarily matter how fast `to-transient` and `to-persistent!` are because we call them rarely.  We are much more concerned with how the engine performs when processing bulk numbers of items at a time in a single insert + fire rules call.  However, there may be an argument that users may want to use Clara in a "streaming" style where batches of facts come separately and need to insert + fire rules + return to the caller efficiently.
I'd say at this point in time though, Clara's local memory and engine implementation favor the approach of inserting + firing rules in bulk instead of many smaller batches.  This change just makes this divide more extreme.

There are ways to try and get the "best of both worlds" here though.  The idea being that we could attempt to defer converting memory to transient or persistent on an as-needed basis.  This can be done, but there are complications.  On the `to-persistent!` side, it gets a little uglier to try to defer converting mutable collections to persistent ones.  The reason I say this is just because this is what the consumer directly has visibility to.  It would seem nicer if we could return common Clojure data structures all the way down at this point. If we attempt to defer on this side, we'd have to have our own new types returned that would presumably be seqable and translate to Clojure persistent data structures when any area of memory was explicitly accessed.

On the transient side, things are bit easier.  We can just continue to store persistent data structures in memory, until they have the need of being changed.  When we call `to-transient` all persistent data structures in memory are left alone.  When removing or adding to these persistent structures, the auto-convert to mutable collection types for the rest of the life of the transient local memory state. 

When we call `to-persistent!` we convert to persistent only those parts of memory that are not already persistent data structures.  This can save time in practice since presumably only a small portion of memory is changed at a time, so a lot of the memory can be left alone in the mutable to persistent and vice versa path.

The downside is more complexity, as well as potentially still having the same performance degradation in the worst-case scenario.  That is if a significant portion of total working memory is changed every time the rules have insertions and are fired anyways.  I'd argue if existing working memory was changed extensively in each insert + fire rules call though, the rete algorithm may start to have deteriorating value since all of its stored state would continually be invalidated and need to be recomputed.

-----

I'd be happy to see what you think about all of this.  If you want to see something more concrete, I can post a few links to commits that show various approaches I've taken to the above.  For now I'll leave it off.

**Comment by rbrush** [comment]
I think we should optimize based on hard data for the workloads we have, and tune for other workloads when data arises showing a problem. I'd speculate that many of the "streaming" style workloads, with frequent transient-persistent transitions, have relatively small sessions and this might not even be a problem. So I'd prefer not to add complexity to support both of these loads until we have good evidence it's necessary. In other words, let's strongly tune for the workloads we know about and we can adjust that in the future. This also applies to the CLJS load.

One option we could pursue, either now or in the future, is to have multiple implementations of the WorkingMemory, with a reasonable default and allow the caller to specify the working memory implementation when constructing the session. It would have a reasonable default, of course, but a caller with specialized knowledge of the workload could choose something better for that case. We could add functionality in the future that swaps out the working memory implementation for a given session at runtime if, for instance, we see more than X transient versions of it created...but that should also be deferred until we have concrete evidence showing its benefit.

So my suggestion for now is to either 1.) strongly optimize the current implementation for your load, which we can refactor later or 2.) Create a new WorkingMemory implementation exclusively optimized for it (and perhaps not even with CLJS support at all), and enhance mk-session so the caller can provide a working memory (or a function that creates a working memory). I think either one is a reasonable path, based on hard data, with the ability to improve in the future.

**Comment by mrrodriguez** [comment]
Thanks for the feedback!  I'll be looking to get a pull request out for this today or tomorrow.
I believe for now I will be doing a single WorkingMemory still since it is fairly straightforward to use read-conditionals for the clj vs cljs divide still.  I also don't think I've significantly hurt the transient-persistent transition yet in a way that I think would be too aggressive.  

I definitely think that you are correct that multiple memory implementations may be the way to go if we do get to a point where we are trying to optimize for these use-cases that differ quite a bit in where the performance bottlenecks are at.

**Comment by rbrush** [comment]
All child tasks for this were closed, so I'm closing this. We can open a new issue for anything else we want to do.
