### ISSUE TITLE
Investigate rule order

### ISSUE THREAD

**Issue by WilliamParker** [rbrush/clara-rules#192]
FYI, I am starting to look into using rule ordering by the order the compiler receives them in the absence of explicit salience as a way to improve performance and increase consistency of execution times from run to run.   Apart from the overall performance averages, inconsistency has made diagnosing performance problems difficult and making runtimes more consistent would be helpful.  @rbrush , you've mentioned rule order a while ago as a potential performance enhancement; have you looked into it any more since then?  I'd prefer to avoid duplication of work.

**Comment by mrrodriguez** [comment]
I'll add that I've implemented a working (at least in our tests) pass at rule load order. However I showed it to Will but there is further work we can do to improve on it. 
So this isn't something we haven't looked at at all already. I had some early performance testing runs etc. It just needs more polish and more comparisons.  

Any thoughts or work Ryan has done towards this would certainly be valuable to see/hear about though!

**Comment by rbrush** [comment]
I haven't done any specific work on this (other than commenting on how we could use some work I think @mrrodriguez did earlier on internal salience). So there won't be any duplication from my end. (And thank you for looking at this!)

**Comment by WilliamParker** [comment]
I have submitted a pull request at https://github.com/rbrush/clara-rules/pull/197 with discussion of the implementation there.

**Comment by WilliamParker** [comment]
I am closing the issue since the pull request has been merged and I don't think there is anything else to do here.
