### ISSUE TITLE
Ignored constraint in rule condition

### ISSUE THREAD

**Issue by mrrodriguez** [rbrush/clara-rules#194]
This seems to silently ignore a constraint of the condition:

```clj
(let [r (dsl/parse-rule [[Temperature
                          (= ?v (+ temperature 5))
                          (< ?v 10)]]
                        (println ?v))
      s (mk-session [r])]

  (-> s (insert (->Temperature 1 "m")) fire-rules)
   (-> s (insert (->Temperature 10 "m")) fire-rules))

;; prints
;; 6
;; 15

;;; Adding a print to the ignored constraint shows it unevaluated entirely.

(let [r (dsl/parse-rule [[Temperature
                          (= ?v (+ temperature 5))
                          (do (println "hello!") (prn ?v) (< ?v 10))]]
                        (println ?v))
      s (mk-session [r])]

  (-> s (insert (->Temperature 1 "m")) fire-rules)
  (-> s (insert (->Temperature 10 "m")) fire-rules))

```

I'd expect either the compiler to fail with a meaningful exception, or for the constraint to be evaluated and tested for the condition.

**Comment by rbrush** [comment]
Seems like the best approach here would be to make a variable bound in a constraint visible to subsequent constraints. I'll take a look at adding such logic to clara.rules.compiler/compile-condition, detecting instances of subsequently used variables and wrapping the generated code of subsequent constraints with a let binding containing the variable

**Comment by mrrodriguez** [comment]
that sounds like a good approach. I think this could be a potentially useful feature. I've seen people expect it to work before and get confused too.

**Comment by rbrush** [comment]
The above commit makes bound variables visible in subsequent constraints under the same condition as described in my previous comment. This fixes the originally reported issue and has a more intuitive behavior. 

I don't think this breaks any existing code, and all tests pass without changes. I'll probably merge this into master in the next day or so unless there are objections.

**Comment by rbrush** [comment]
Rebased and merged to into master in the above commit. Closing since there is nothing more to do with this one.
