### ISSUE TITLE
Iteration over maps and sets in the compiler can cause non-deterministic compilation

### ISSUE THREAD

**Issue by WilliamParker** [rbrush/clara-rules#199]
We have experienced dramatically different times in the execution of the same rules on the same data; for example, we've seen fluctuations from under 10 seconds to over 30 seconds when we repeatedly restart the JVM.  However, execution times seems to be more consistent when using the same JVM.  This leads me to suspect that differences in rulebase compilation are responsible for the fluctuation. Since Clara caches sessions, unless caching is disabled or the cache is manually cleared the rulebase used for a given set of rules will remain the same, but a JVM restart will force it to clear.

This sort of non-determinism poses problems for us in that

1. It makes it difficult to replicate and diagnose performance problems.
2. It could result in intermittent timeouts, although so far we have not had this problem.

I suggest that ensuring fully deterministic rulebase compilation would be desirable.  As a first step toward this, I suggest that when we iterate over sets and maps in rulebase compilation that these sets and maps be sorted, since iteration over the non-sorted versions of these data structures has undefined ordering.  I have an example of this type of change at https://github.com/WilliamParker/clara-rules/commit/18d8ac821489d82db2382c3ce8299f073d2ecebb

In that commit I changed mk-session* to include sorting of the productions with the following let binding:

````
productions (into (sorted-set-by (fn [a b]
                                           (< (-> a meta ::rule-load-order)
                                              (-> b meta ::rule-load-order))))
                          productions)
````

This uses the rule loader order metadata added in https://github.com/rbrush/clara-rules/issues/192

````
;;; The adding of rule loader order to the productions from issue 192
(map (fn [n production]
                                 (vary-meta production assoc ::rule-load-order (or n 0)))
                               (range))
````
The (or n 0) can actually just be changed to n; everything will have a defined rule order at this point since the seq returned by (range) will not have nil members.  Therefore the set of productions will be given a consistent ordering for all runs for constant ordering of the rules/rule sources passed to the compiler.

I suspect that there will be iterations over a BetaGraph [1] that will require ordering as well.  I'm still looking over the rest of the compiler, but I wanted to raise an issue here before getting too deep into this.

Note that I'm not saying that this will ensure fully deterministic compilation on its own, but it seems like a necessary step that will at least bring us closer to determinism.

1. https://github.com/rbrush/clara-rules/blob/0.11.1/src/main/clojure/clara/rules/schema.clj#L139

**Comment by WilliamParker** [comment]
To clarify - iteration over hash based data structures could be impacted by the JVM instance restarting as well, even if we didn't cache.

**Comment by WilliamParker** [comment]
I have submitted a pull request at https://github.com/rbrush/clara-rules/pull/201 with the following changes:

- The sets of numbers in the value of the :forward-edges and :backward edges of [1] are now sorted.  I don't actually think this ends up mattering as currently implemented, since the usage at [2] just uses these sets as keys to select on the :id-to-node map and I made finding the set of common child nodes in add-conjunction [3] deterministic without it as discussed below. It just seems like a better practice and more resilient to future changes to make the BetaGraph [1] structure itself entirely sorted.
- The maps in the empty-beta-graph are all now sorted.
   - In the case of :id-to-condition-node, I believe this matters because to-alpha-graph will use the order of :id-to-condition-node to determine the ordering of the children [4], which is reflected in the compiled alpha nodes [5], which determines the order that the engine will activate the children. [6]
   - I don't see anywhere where the others matter, but I just think that future modification will be easier/more reliably consistent if we can depend on the overall beta graph being sorted.
- In add-conjunctions, when we have multiple common child IDs, I sorted the set of "common-children-ids" so that the "existing-id", if any, chosen will be deterministic even in any edge cases where the same (as in Clojure equal data structures) node occurs under multiple IDs.  This is more to be deterministic in case of any potential bugs here than for performance, although it could impact both, but it seems like something that should do no harm and could be helpful.
- The map returned by compile-beta-graph [7] is now sorted.  This is needed so that the beta-roots in the rulebase will have a deterministic order [8], which is the order in which they will be left-activated by the empty token. [9]
- I made changes to to-alpha-graph so that the alpha nodes will be returned in a deterministic order.  Specifically, conditions are sorted by the sum of the node-ids.  I don't see any obvious heuristics to improve performance here by choosing a particular ordering, so I just went with something simple that will be deterministic if node IDs are the same.  If anyone has thoughts on a useful heuristic for this I'd be interested.  This ordering matters because the ordering here is the ordering used in the alpha map of the rulebase [10], and for any given type this is the order in which the alpha nodes will be activated. [11, 12]  Note that there is still some nondeterminism in the alpha roots if the ordering of the ancestors can change, but that is not in the rule network so I'd consider that out of scope here. [13]
- The set of productions will now be sorted by the load order.  This is necessary to make the node-id consistent, since we a stateful ID counter on a reduce over all productions. [14]

#### Remaining known sources of inconsistency:

- As mentioned above, the alpha nodes for a single type are expected to be in a consistent order, but if a type C gets the alpha nodes for types A and B, then there may be some nondeterminism in whether the the nodes sequence that is doseq'ed over looks like

````
(concat type-a-alpha-nodes type-b-alpha-nodes)
;; or
(concat type-b-alpha-nodes type-a-alpha-nodes)
;; Note that this is just convenient notation.  I'm not saying this is actual code in Clara.
````
The type can be any arbitrary value, and there may not be any valid comparisons that can be made between types.  Since we cache on the types we probably wouldn't have much runtime cost
from some change here though, whatever that change might me.
- There are various places in the engine where we iterate over return values from tuned-group-by [15]; this seq order will be nondeterministic.  Any ordering here would have to be considered carefully for possible overall performance degradation since it would impact runtimes after rulebase creation.

#### Other notes:

- I believe node IDs should be consistent now, and have uncommented the test for node consistency.  However, I suspect that many potential sources of inconsistency would be consistent within the same JVM, so to more thoroughly test this would probably would require a test runner to start multiple JVMs and validate the node IDs.
- Overall, while there is still significant variation from run to run, we had significantly increased consistency when I pulled the worst cases from our processing jobs and compared which subset of the data each case used and how long it took with these changes.


1. https://github.com/rbrush/clara-rules/blob/0.11.1/src/main/clojure/clara/rules/schema.clj#L139
2. https://github.com/rbrush/clara-rules/blob/0.11.1/src/main/clojure/clara/rules/compiler.clj#L1301
3. https://github.com/rbrush/clara-rules/blob/0.11.1/src/main/clojure/clara/rules/compiler.clj#L965
4. https://github.com/rbrush/clara-rules/blob/0.11.1/src/main/clojure/clara/rules/compiler.clj#L1340
5. https://github.com/rbrush/clara-rules/blob/0.11.1/src/main/clojure/clara/rules/compiler.clj#L1404
6. https://github.com/rbrush/clara-rules/blob/0.11.1/src/main/clojure/clara/rules/engine.cljc#L101
7. https://github.com/rbrush/clara-rules/blob/0.11.1/src/main/clojure/clara/rules/compiler.clj#L1263
8. https://github.com/rbrush/clara-rules/blob/0.11.1/src/main/clojure/clara/rules/compiler.clj#L1486
9. https://github.com/rbrush/clara-rules/blob/0.11.1/src/main/clojure/clara/rules/engine.cljc#L1220
10. https://github.com/rbrush/clara-rules/blob/0.11.1/src/main/clojure/clara/rules/compiler.clj#L1408
11. https://github.com/rbrush/clara-rules/blob/0.11.1/src/main/clojure/clara/rules/compiler.clj#L1460
12. https://github.com/rbrush/clara-rules/blob/0.11.1/src/main/clojure/clara/rules/engine.cljc#L165
13. https://github.com/rbrush/clara-rules/blob/0.11.1/src/main/clojure/clara/rules/compiler.clj#L1452
14. https://github.com/rbrush/clara-rules/blob/0.11.1/src/main/clojure/clara/rules/compiler.clj#L1098
15. https://github.com/rbrush/clara-rules/blob/0.11.1/src/main/clojure/clara/rules/platform.cljc#L10

**Comment by devn** [comment]
I might be way off base here, but I seem to recall that we saw cache misses where we didn't expect them. We have a `collect-sources` function for the purposes of accepting both the namespaces where rules live, and dynamically generated rules which looks sorta like this:

```clojure
(defn collect-sources
  [sources]
  (reduce (fn [res source]
            (cond
              (symbol? source)
              (concat res (com/load-rules source))

              (sequential? source)
              (into res source)

              :else
              (conj res source)))
          []
          sources))
```

When we dug in, we noticed that the orderings were off. In order to see a cache hit, we simply needed to do this:

```clojure
(-> '[foo.bar foo.baz] (collect-sources) (set) (mk-session :cache true))
```

**Comment by mrrodriguez** [comment]
> I made changes to to-alpha-graph so that the alpha nodes will be returned in a deterministic order. Specifically, conditions are sorted by the sum of the node-ids. I don't see any obvious heuristics to improve performance here by choosing a particular ordering, so I just went with something simple that will be deterministic if node IDs are the same. If anyone has thoughts on a useful heuristic for this I'd be interested. This ordering matters because the ordering here is the ordering used in the alpha map of the rulebase [10], and for any given type this is the order in which the alpha nodes will be activated. [11, 12] Note that there is still some nondeterminism in the alpha roots if the ordering of the ancestors can change, but that is not in the rule network so I'd consider that out of scope here. [13]

See https://github.com/rbrush/clara-rules/pull/201/files#r66372547

> There are various places in the engine where we iterate over return values from tuned-group-by [15]; this seq order will be nondeterministic. Any ordering here would have to be considered carefully for possible overall performance degradation since it would impact runtimes after rulebase creation.

Outside of the scope of this issue for sure.  However, I want to make it a note that `tuned-group-by` could probably use java.util.LinkedHashMap to meet this need.  I'm pretty sure the insertion order of creating this map is deterministic.  Then once we have it, we always just seq over it (pretty sure on that).  LinkedHashMap meets this need dead on it looks like.  The overhead of the insertion order of it looks to be minimal too according to the docs.  Insertion is only slightly more expensive and iteration over the entries is potentially faster.  That's probably a good balance for our needs.

**Comment by devn** [comment]
@WilliamParker apologies, I re-read your issue and realized I missed some of the context. When reading it seemed as if you might be conflating ordering with the check on the cache, but I understand the rationale now. Even if that had been the case, there are several good reasons for preferring what you're proposing. My response was more of a reaction to what seemed like missing benchmarks, but I realize now that these benchmarks are problematic to reliably produce for exactly the reason you've opened this issue.

**Comment by WilliamParker** [comment]
No need for apologies @devn :)

FYI, the cached session had to have the same rules order to have a hit before https://github.com/rbrush/clara-rules/issues/157 

Were your problems before that?  Also, the options have to be the same according to Clojure equality for there to be a cache hit.  So if you did something like

````
(mk-session rules-here :activation-group-sort-fn (fn-factory-returning-different-objects))
````

you'd always have misses since the function objects would not be equal.

I don't think these changes would change caching behavior since the caching is done in clara.rules.compiler/mk-session, while the highest level of these changes in the call stack is clara.rules.compiler/mk-session*.  mk-session calls mk-session* if there is a cache miss.

**Comment by WilliamParker** [comment]
I don't think there is anything more to do here since https://github.com/rbrush/clara-rules/pull/201 has been merged.  Closing.
