### ISSUE TITLE
Add test helpers for creating random insert/retract/fire-rules patterns

### ISSUE THREAD

**Issue by WilliamParker** [rbrush/clara-rules#205]

**Comment by WilliamParker** [comment]
https://github.com/rbrush/clara-rules/pull/206

This pull request adds some test helpers to create randomly generated insert/retract/fire patterns and to run those patterns on sessions.  It also adds a test profile for running generative tests and turns off running those tests for the main "lein test" command.  For now it runs the generative tests as part of the Travis build, but this could be revisited in the future if we write lots of expensive generative tests.  Both the generative and main test builds still run the ClojureScript tests. The generative build shouldn't need to do so but I haven't yet found a good way to change this behavior, and it is a short amount of time for them to run anyway.  My main reason for separating out the generative tests is that it seems likely that generative testing will take significantly longer to run and will probably be run less often in development.

For now the facts, productions, and assertions involved have to be manually specified.  My immediate use-case for these is testing of insert-retract patterns on accumulators.  With some work I'm doing on AccumulateNode I think I have all (known) bugs there addressed, and I plan to write some generative tests on AccumulateNode behavior.  My concern with the existing tests is that empirically, there seem to be a number of errors I've made that did not cause Clara tests to fail and were caught later, whether by looking through the code again, running our internal rules test suites, finding differences when I tried the new code on our production datasets, etc.  I'm hoping that a more generative style of testing can catch problems, particularly edge cases, more reliably.

Possible future improvements to generative testing include:

- Random generation of productions and/or facts
- Randomly grouping insertions and retractions differently.  For example, 

````
{:type :insert
 :facts [:a :b]}
 ````

 should be equivalent to

 ````
 {:type :insert
 :facts [:a]}
 {:type :insert
 :facts [:b]}
 ````

 I wanted to get some feedback on this approach before diving in too deep writing tests
 using it.  @rbrush  @mrrodriguez  and anyone else interested.  I recall @devn had some interest in generative testing from a conversation on the Slack channel as well.

**Comment by rbrush** [comment]
I love the idea, and agree that starting with targeted needs (like your accumulator work) and growing from there is the right path.

I haven't used generative testing in Clojure in earnest, but this seems promising. I have poked around Clojure's test.check library and it seems capable of generating sequence permutations of record or enumeration types (as well as any other primitive), as described here: https://github.com/clojure/test.check/blob/master/doc/intro.md. Not sure if that's a good fit or not for your immediate goals.

**Comment by WilliamParker** [comment]
My current thought is that test.check isn't a great fit for my current goals.  Currently, this just varies the ordering of inserts, retracts, and rules firing, with potential for future variation of grouping of insert and retract calls.  The actual rules, data, and assertions are fully user-specified.  In our special use-case, we have the advantage that we know that ordering of these things should not impact the logical outcome at the end (setting aside any arbitrary RHS code, unconditional insertions, and RHS retractions).  Randomly generating rules and data would certainly be nice, but also generating assertions for those generated rule/data combinations is a nontrivial problem.  This approach avoids most of the difficult problems with generating data and assertions.

Test.check seems like it would be better for sampling from a large sample space on repeated runs, where it would be impractical to run all possibilities in a given run.  Random facts and rules would be an extremely large input space, most likely even with some constraints.  My goal with these helpers was to exhaustively test a far smaller user-specified input space.  I suspect that a relatively small number of variations (perhaps thousands or tens of thousands) on a handful of facts and rules would suffice to strengthen the test suite significantly, but this is just a guess that could be wrong.  Random case generation seems like it would require more care in ensuring that the distribution of cases selected is representative as well.  If I'm missing a way in which test.check would be useful though I'm certainly open to suggestions.

**Comment by rbrush** [comment]
Ah, I had overlooked that your goal was to specifically test each combination each time, and had assumed you were just generating permutations. What you're doing makes sense (and I'm fine with merging this in even in it's early phases), and perhaps broader test.check usage comes later.

**Comment by mrrodriguez** [comment]
I had a few smaller comments on the PR.

Overall I think this is good.  It is a good start to this sort of idea.  test.check stuff is interesting to, but I think it solves a different problem then this initial pass it working towards.

**Comment by WilliamParker** [comment]
There is room for future improvement, but I think such improvements probably belong in separate issues and that everything that belongs in this issue has been addressed with the merge of https://github.com/rbrush/clara-rules/pull/206
