### ISSUE TITLE
Token and activation retraction with identity equality checking first

### ISSUE THREAD

**Issue by mrrodriguez** [rbrush/clara-rules#213]
In https://github.com/rbrush/clara-rules/issues/184 we improved the performance time of the "transient" state of Clara's local memory implementation by utilizing mutable collections for hot paths of retraction/insertion flows.  During the "fire rules loop" there can be a lot of quick changes to memory and this has proven to pay off significantly in many of our production workflows.

This issue is addressing a similar concern.

-----

It has been observed when troubleshooting some scenarios that a lot of time can be spent performing token and activation retractions still.  In #184 the problem was the persistent collections we were using were just too slow to remove items from the middle/rebuild/etc.  The issue now is in the way that we perform our search to retract tokens and activations.  Clara retraction embraces value-based-equality semantics.  The caller can do something like:
```clj
(let [s (mk-session my.rules)]
  (-> s (insert (->Hot 10)) (retract (->Hot 10)) fire-rules))

```
The important part above, is that there are actually 2 object instances of Hot.  They are both equal, in a value-based sense, but they are not the same identity references.  The caller would expect the first instance of Hot to be removed by the second instance of Hot here though.

This feature of Clara is reasonable and arguably the "right" way to do it according to Clojure's philosophy and idioms.

There is a price to pay for using value-based-equality throughout the engine though.  Equality can get expensive.  A token has `:matches`, which may contain fairly large numbers of the domain specific facts that are meeting conditions in working memory.  A single condition can have very large collections matching it via accumulators.  There can also just be rules that have been activated many times over, with many tokens and many activations batched up in memory.  When something changes to this working memory state, such as truth maintenance changes (very common) or explicit RHS retractions (less common), there can be a lot of tokens and activations to "clean-up" via retraction.

-----

I still am wanting to explore a true "asymmetrical" retraction model for Clara's memory.  However, there is a quicker and easier way to address the primary concern here.

Clara can continue to support the value-based equality semantics, while still taking advantage of the much faster and object size independent object-identity-based equality where it makes sense.

When working memory is being rapidly updated due to truth maintenance and new rules being fired etc, the tokens we are retracting and inserting are always holding references to the exact same objects in memory.  This means they are all primarily identity-based equal.

I plan to post up a PR for this shortly.  The PR is taking advantage of the point above.  Object identity at the fact-level is checked first when searching for tokens or activations to retract.  If tokens or activations do not find a match on object-identity equality, it falls back to value-based equality to be sure we are still supporting value-based semantics when it does matter.  This fallback should rarely/if ever occur in "fire rules loop" scenario.

With these changes, we have observed significant time savings in our heavier working memory loads.  It also has helped the overall average across several of our production rulebases.

-----

I'm posting this up as an issue here to describe the motivation and to have a place to discuss this more if needed.

**Comment by mrrodriguez** [comment]
PR is https://github.com/rbrush/clara-rules/pull/214

**Comment by rbrush** [comment]
Closing, since the PR has been merged.
