### ISSUE TITLE
`derive` against global hierarchy prevents `fire-rules` from terminating

### ISSUE THREAD

**Issue by noprompt** [rbrush/clara-rules#217]
This one is a bit tricky and the best way I can demonstrate it is with code. Consider the following code.

```clj
(ns example
  (:require [clara.rules :as clara]))

(clara/defrule valid-test-result
  [?test-result <- ::base [test-result]
   (= true (:valid? test-result))]
  =>
  (clara/insert!
   (assoc ?test-result :tag ::valid)))

(clara/defrule invalid-test-result
  [?test-result <- ::base [test-result]
   (= false (:valid? test-result))]
  =>
  (clara/insert!
   (assoc ?test-result :tag ::invalid)))

(clara/defquery valid-test-results []
  [?test-result <- ::valid])

(clara/defquery invalid-test-results []
  [?test-result <- ::invalid])
```

If we then execute (in the same namespace)

```clj
(do
  (derive ::valid ::base)
  (derive ::invalid ::base)

  (->
   (clara/mk-session (ns-name *ns*) :fact-type-fn :tag)
   (clara/insert-all [{:tag ::base :valid? true}
                      {:tag ::base :valid? false}])
   (clara/fire-rules)))
```

the (REPL) session will freeze as `fire-rules` does not terminate.

However if we execute the operations in the `do` block in reverse

```clj
(do
  (->
   (clara/mk-session (ns-name *ns*) :fact-type-fn :tag)
   (clara/insert-all [{:tag ::base :valid? true}
                      {:tag ::base :valid? false}])
   (clara/fire-rules)
   (clara/query invalid-test-results))

  (derive ::valid ::base)
  (derive ::invalid ::base))
```

the (REPL) session will not freeze and `fire-rules` will terminate successfully. It's unclear to me why the order of execution matters.

I did some poking around the code looking for occurrences of `isa?` and the ones I found in the compiler ([here](https://github.com/rbrush/clara-rules/blob/13537dbea4ef7a199c95982bf34b3b26ccba7757/src/main/clojure/clara/rules/compiler.clj#L167) and [here](https://github.com/rbrush/clara-rules/blob/13537dbea4ef7a199c95982bf34b3b26ccba7757/src/main/clojure/clara/rules/compiler.clj#L1498)) do not seem suspect at face value. It's not immediately obvious to me if this is a bug in Clara or a bug in Clojure.

I also tried temporarily rebinding `clojure.core/global-hierarchy` to a custom hierarchy but that doesn't seem to prevent the problem from happening.

**Comment by noprompt** [comment]
I've also verified this problem _does not_ occur when running the failing code from `lein run -m`.

**Comment by noprompt** [comment]
This is the minimum failing test case. Sorry for all of the noise on this issue!

```clj
(ns a
  (:require [clara.rules :as clara]))

(clara/defrule valid-test-result
  [?test-result <- ::base [test-result]
   (= true (:valid? test-result))]
  =>
  (clara/insert!
   (assoc ?test-result :tag ::valid)))

(derive ::valid ::base)

(->
 (clara/mk-session (ns-name *ns*) :fact-type-fn :tag)
 (clara/insert-all [{:tag ::base :valid? true}])
 (clara/fire-rules))
```

**Comment by rbrush** [comment]
So I think what's happening here is that the ```derive``` call makes it so that ```::valid``` "is a" (inherits from, to use the OO terms) base...so this rule goes into an infinite loop because its right-hand side inserts a ::valid, which then matches the left-hand side, which triggers the right-hand side, and so on. So this example is working as I would expect. Unfortunately, forward chaining rules don't have a great answer to this sort of thing.

Of course, if derive isn't called before had, the ::valid is *not* a ::base per Clojure's type hierarchy...so Clara won't match it.

**Comment by noprompt** [comment]
@rbrush I think I failed to mention that in the case that `derive` is called _after_ running `clara/fire-rules` subsequent calls to `clara/fire-rules` will terminate. Here is an example demonstrating the behavior:

```clj
(ns a
  (:require [clara.rules :as clara]))

(clara/defrule valid-test-result
  [?test-result <- ::base [test-result]
   (= true (:valid? test-result))]
  =>
  (clara/insert!
   (assoc ?test-result :tag ::valid)))
;; => #'a/valid-test-result


(clara/defquery valid-test-results []
  [?test-result <- ::valid])
;; => #'a/valid-test-results

(->
 (clara/mk-session (ns-name *ns*) :fact-type-fn :tag)
 (clara/insert-all [{:tag ::base :valid? true}
                    {:tag ::base :valid? false}])
 (clara/fire-rules)
 (clara/query valid-test-results))
;; => ({:?test-result {:tag :a/valid, :valid? true}})

(derive ::valid ::base)
;; => nil

(->
 (clara/mk-session (ns-name *ns*) :fact-type-fn :tag)
 (clara/insert-all [{:tag ::base :valid? true}
                    {:tag ::base :valid? false}])
 (clara/fire-rules)
 (clara/query valid-test-results))
;; => ({:?test-result {:tag :a/valid, :valid? true}})
```

Perhaps there's an explanation for this but it seems strange. Is it a caching problem?

One question I'm left with is why `isa?` would be a factor at all. The two places in the compiler where `isa?` is used do not seem to present an issue. I see no other connection to any of the hierarchical family of functions (ie. `derive`, `descendants`, `ancestors`, `parents`) in the code except for the one [here](https://github.com/rbrush/clara-rules/blob/fd405a71d8bcefbdc82da17db52c63bc5427357b/src/main/clojure/clara/rules/engine.cljc#L37) which would appear innocent.

**Comment by rbrush** [comment]
The ancestors of a type are cached here:

https://github.com/rbrush/clara-rules/blob/fd405a71d8bcefbdc82da17db52c63bc5427357b/src/main/clojure/clara/rules/compiler.clj#L1515

Clara caches that so it doesn't have to look at the transitive closure of every ancestor for every type every time we want to match a rule. So the (derive ...) after a session is created won't affect the types of that session.

**Comment by noprompt** [comment]
So it appears that `:ancestors-fn` can be passed in `mk-session` though the docstring doesn't specify that. Is that by design? If the heart of the problem is indeed with the `ancestors-fn` then we could work with that by specifying our own in such a way that we avoid this issue. We can also specify our `derives` in a separate hierarchy but as you can imagine it'd be preferable to avoid that if possible.

**Comment by rbrush** [comment]
Yeah, looks like an oversight on the mk-session doc string. I don't see any reason we wouldn't include the ```:ancestors-fn``` option as part of that API, since we're allowing custom types. (We can use this issue to track that change if you like.)

I don't know of other users using a specialized ancestors-fn. Normally I'd be reluctant to go down a less-traveled path, although it sounds like you have something of a special case that looks to dynamically create types and hierarchies, but not use them Clara.

**Comment by noprompt** [comment]
Thanks, that would be awesome. It turns out that by simply specifying `:ancestors-fn (constantly [])` resolved the problem in our experiment. This was a subtle gotcha, your help with this is greatly appreciated!

We actually do have a use case for hierarchies but the semantics are closer to that of a tagged union where the members have identical fields but are logically different. As we have a great deal of diversity with respect to data types and their logical variants creating records to accommodate them becomes cumbersome; it's easier to use a vanilla map or a single record type with a field for the variant tag. Inside the rules engine the hierarchy is not especially useful but outside of it is e.g. `(filter #(isa? ,,,)` so it's nice to be able to use both.

**Comment by rbrush** [comment]
Glad I could help!

I added documentation to the ```:ancestors-fn``` option to the mk-session Clojure doc in the above commit. I don't think there's anything more to do here, so I'm going to close this in preparation for a 0.12 release. We can create new issues if there's anything more to do here.

Thanks,
Ryan
