### ISSUE TITLE
Retractions from external insertions and retractions are not batched

### ISSUE THREAD

**Issue by WilliamParker** [rbrush/clara-rules#225]
Currently, when we retract a fact externally, it is removed and then all transitive logical insertions from that fact are immediately retracted. [1, 2]  So, for example, if we have code like the following:

````
(defrule rule-1
   [?a <- FactA]
   =>
   (insert! (->FactB)))

(defrule rule-2
   [?b-facts <- (acc/all) :from [FactB]]
   =>
   ;; do something)

````
and do something like

````
(-> session (insert-all (for [_ (range 10)] (->FactA)))
            fire-rules
            (apply retract (for [_ (range 10)] (->FactA))))
````

when the retraction occurs, Clara will retract one FactA, retract one FactB, and re-accumulate. This will occur for each FactA that is retracted.  It would be more efficient to retract all the FactA facts at once, then retract all the FactB facts, and then reaccumulate on the FactB condition in rule-2.  This is similar to the approach used when facts are inserted and retracted in a fire-rules call [3, 4].

I've written a prototype of such batching at https://github.com/WilliamParker/clara-rules/commit/115e0673513a55490d0894d97fe45f863807f5e8.  Note that it batches retractions from external insertions as well as retractions.  An external insertion that matches an accumulator condition can cause logical retractions if it changes the accumulated value.  Similarly, an external insertion that matches a negation condition can cause logical retractions for obvious reasons.  These retractions will be immediately fully realized [2].

We have seen a retraction of a fact used in many rules perform poorly that then had performance improve greatly when this batching strategy was used.  It probably merits some more thought before a merge, but right now I don't see much reason to immediately realize everything in external operations and batch operations in the fire-rules loop, and if batching is correct in the latter case it should be correct in the former case as well.

1. https://github.com/rbrush/clara-rules/blob/0.13.0-RC2/src/main/clojure/clara/rules/engine.cljc#L1515
2. https://github.com/rbrush/clara-rules/blob/0.13.0-RC2/src/main/clojure/clara/rules/engine.cljc#L296
3. https://github.com/rbrush/clara-rules/blob/0.13.0-RC2/src/main/clojure/clara/rules/engine.cljc#L1394
4. https://github.com/rbrush/clara-rules/blob/0.13.0-RC2/src/main/clojure/clara/rules/engine.cljc#L156

**Comment by mrrodriguez** [comment]
+1 the changes make sense to me.

This seems like it has potential for significant performance improvements.  We know we saw a few already with an external retract workflow.

**Comment by rbrush** [comment]
Yep, this makes sense. The only reason this wasn't implemented earlier is that use cases weren't performing retractions very often so it wasn't something I spent time on. I'll be happy to merge a pull req along these lines once one is ready.

**Comment by WilliamParker** [comment]
Pull request submitted at https://github.com/rbrush/clara-rules/pull/226

It is basically the same as the prototype I linked to previously with a little cleanup of the changes in engine.cljc and some tests added for paths changed by this that I didn't see existing tests for.

**Comment by WilliamParker** [comment]
I don't see anything left to do here since the PR has been merged.  Closing.
