### ISSUE TITLE
Store the memory in a more efficient way.

### ISSUE THREAD

**Issue by ylando2** [rbrush/clara-rules#30]
If this rule engine is going to be used on local computer, the bottle neck is going to be the memory handling.
Maybe we need to create one file that is optimize for the jvm and another for JavaScript.

**Comment by rbrush** [comment]
This has been done as a byproduct of other efforts, so I'm going to go ahead and mark it as closed. The working memory now uses CLJC with optimizations for both the JVM and JavaScript. We can open new issues for further memory optimizations.
