### ISSUE TITLE
Alternative implementation without using (tuned-)group-by

### ISSUE THREAD

**Issue by andrew-nguyen** [rbrush/clara-rules#62]
I was looking through the implementation a little bit and curious about the underlying implementation details.  I noticed that you essentially group everything by type (or the output of fact-fn-type).  Long term, I'd like to be able to have rules trigger by the elements within a set and it's not entirely obvious to me how to do that.

For example, I have maps that contains a set of values:

```clojure
{:attributes #{:attr1 :attr2} :name "some name"}
```

And I'd really like to create a rule similar to:

```clojure
(defrule some-rule
  [?obj <- (contains? :attr1)] => (println (:name ?obj))
```

where the fact-type-fn is just ```:attributes```

Currently, I'm wrapping the map with a record that provides similar functionality but it definitely won't scale as the set grows and also pushes the matching into the rule itself.  I'd like to bring this up so that I can avoid the initial rule match.

The other approach I thought about taking was to duplicate the facts, one per value of the :attributes set but this started to cause other problems for me unrelated to clara-rules.

I understand this may be an implementation that isn't of interest to others so I'm happy to take a stab at it.  But, I wanted to check in and see if you had any comments/suggestions so I don't end up learning the same lessons the hard way.

**Comment by rbrush** [comment]
I'm going to go ahead and close this as I don't think there is anything to do here. We can reopen or create a new issue if anyone disagrees.
