### ISSUE TITLE
Rules with negation logic not retracting facts correctly.

### ISSUE THREAD

**Issue by gofeddy** [rbrush/clara-rules#83]
I noticed that when I have a rule with a negation logic (i.e. a rule that looks at the absence of a fact in the session), it doesn't seem to be working as expected with how we'd expect retraction to work.

I have an example to explain the scenario I'm seeing:

```
;; inside namespace ns.rules

(s/defrecord A [])
(s/defrecord B [val :- s/Num])
(s/defrecord C [val :- s/Num])

(defrule ab-rule
  [A]
  =>
  (insert! (->B 100)))

(defrule bc-rule
  [B (= val 50)]
  =>
  (insert! (->C 1)))

(defrule bc-rule-neg
  [:not [B]]
  =>
  (insert! (->C 0)))
```

Here's a test case that I have that tries to validate the rule logic:

```
(deftest negation-rule-test
  (let [query (dsl/parse-query [] [[?c <- C]])        
        
        session (tr/with-tracing (sr/mk-session [ab-rule
                                                 bc-rule
                                                 bc-rule-neg
                                                 query]))
                
        session-after-rule-firing (-> session
                                      (sr/fire-rules)
                                      (sr/insert (->A))
                                      (sr/fire-rules))
        
        facts (-> session-after-rule-firing
                  (sr/query query)
                  (set))]
    
    (is (= 0 (count facts)))
    (println facts)
    (clojure.pprint/pprint (tr/get-trace session-after-rule-firing))))
```

So when I run this test, it fails indicating that `(count facts)` is 1 and not 0.  I would expect that the `(count facts)` to be 0 because of how the rule logic should work:
* Initially, I'm firing rules without inserting anything. This should cause the `bc-rule-neg` rule to be fired, which should insert fact C with :val 0.
* Then I'm inserting fact A. This should cause the `ab-rule` to fire, causing fact B with :val 100 to be inserted.
* This should activate the `bc-rule`, however since the constraint match fails(100 != 50), it will not insert fact C.
* Around the same time, I would expect the `bc-rule-neg`'s LHS to no longer match since there exists a fact B, causing fact C with :val 0 to now be retracted. Instead what I see is that this retraction doesn't seem to be happening and the fact continues to exist in the session.

There's possibly an issue with how negation is working in this specific scenario.

Here's the results from the test (Note I have tracing results being printed out as well):

```
=> facts: 
#{{:?c #ns.rules.C{:val 0}}}

=> tracing results
[{:type :add-facts-logical,
  :token {:matches [], :bindings {}},
  :facts ({:val 0})}
 {:type :right-activate,
  :node-id 3,
  :elements ({:fact {:val 0}, :bindings {:?c {:val 0}}})}
 {:type :left-activate,
  :node-id 7,
  :tokens ({:matches [[{:val 0} 3]], :bindings {:?c {:val 0}}})}
 {:type :add-facts, :facts ({})}
 {:type :right-activate,
  :node-id 0,
  :elements ({:fact {}, :bindings {}})}
 {:type :left-activate,
  :node-id 4,
  :tokens ({:matches [[{} 0]], :bindings {}})}
 {:type :add-activations,
  :node-id 4,
  :tokens ({:matches [[{} 0]], :bindings {}})}
 {:type :add-facts-logical,
  :token {:matches [[{} 0]], :bindings {}},
  :facts ({:val 100})}
 {:type :left-retract,
  :node-id 6,
  :tokens [{:matches [], :bindings {}}]}
 {:type :remove-activations,
  :node-id 6,
  :activations
  ({:node
    {:id 6,
     :production
     {:name "ns.rules/bc-rule-neg",
      :lhs
      [[:not {:type ns.rules.B, :constraints []}]],
      :rhs (clara.rules/insert! (ns.rules/->C
 0))},
     :rhs
     #<test_rules$eval13745$fn__13746 ns.rules$eval13745$fn__13746@285d8d24>},
    :token {:matches [], :bindings {}}})}]
```

I see that a :left-retract is being done along with :remove-activations, so I don't know what else might be missing here. I haven't dug through the working logic of the engine itself, but I thought I'd post what I was seeing here so it's visible.

Let me know if you need anything else.

**Comment by rbrush** [comment]
The above commit should fix this issue, and a clara-rules-0.9.0-SNAPSHOT with the fix is up on the Sonatype repository. I'll get a fix release out today (probably 0.8.4).

https://oss.sonatype.org/content/repositories/snapshots/

**Comment by rbrush** [comment]
I went ahead and pushed a 0.8.4 release containing this change, which addresses an issue that I'm almost certain causes the behavior described here. Thanks for reporting this!

If this or some other issue persists we can reopen this or log a new one.

**Comment by gofeddy** [comment]
Thanks for the quick fix Ryan! I tested the change and it's working fine now.
