### ISSUE TITLE
Nested constraint variable visibility

### ISSUE THREAD

**Issue by mrrodriguez** [rbrush/clara-rules#90]
The premise is easy, I want to write a rule like this:

```clj
(defrecord MyType1 [x])
(defrecord MyType2 [y])

(defrule my-rule
  [MyType1 (= ?x x)]
  [MyType2 (or (= ?x y)
               (= y 50))]

  =>
  (println "doesn't matter"))

```

When I try this out I get an exception concerning the variable binding `?x` not being visible in the MyType2 constraint:

```clj
(mk-session [my-rule])

;= CompilerException java.lang.RuntimeException: Unable to resolve symbol: ?x in this context, compiling:(/private/var/folders/xj/n5g3pvr94z77j03r39c8lb2w0000gp/T/form-init8355306558764258929.clj:3:30) 

```

Similarly for a fact binding I have the same issue

```clj
(defrule my-rule
  [?m <- MyType1]
  [MyType2 (or (= (:x ?m) y)
               (= y 50))]

  =>
  (println "doesn't matter"))

(mk-session [my-rule])

;= CompilerException java.lang.RuntimeException: Unable to resolve symbol: ?m in this context, compiling:(/private/var/folders/xj/n5g3pvr94z77j03r39c8lb2w0000gp/T/form-init8355306558764258929.clj:3:30) 

```

Interestingly, for an accumulate constraint I can dodge this issue:

```clj

(defrule my-rule
  [MyType1 (= ?x x)]
  [?m2 <- (acc/max :y) :from [MyType2 (or (= ?x y)
                                          (= y 50))]]

  =>
  (println "doesn't matter"))

(mk-session [my-rule])

;= #<LocalSession clara.rules.engine.LocalSession@38602fbb>

```

The same goes for the fact binding in this case.

---

I haven't really tracked much into why an accumulate constraint can be compiled this way.  I'm guessing it goes down a different compilation path.  I think I have tracked down that this issue could be fixed through the `clara.rules.compiler/compile-constraints` function.  The function doesn't account for non-assignment expressions at the top level.

Is there any particular reason why variable bindings cannot be used or bound in nested expression within a constraint on a rule condition?  I think it is a useful use-case.

If nested expressions are made to be supported, I think it would make sense to allow arbitrary tests, not just `=`, with bound variables, since this is allowed for non-nested expressions now.

I'm not sure what workaround can be used to express the rule I initially listed in this post.  I guess it could be possible to split it into two rules.

```clj

(defrule my-rule-1
  [MyType1 (= ?x x)]
  [MyType2 (= ?x y)]

  =>
  (do (insert! ^{:type :my-rule-1} {:did-it true})
    (println "doesn't matter")))

(defrule my-rule-2
  [:not [:my-rules-1]]
  [MyType1 (= ?x x)]
  [MyType2 (= y 50)]

  =>
  (println "doesn't matter"))

```

This is pretty verbose, especially if the conditions were more complex.  I believe it is equivalent though.

---

I'm thinking that this has interesting implications, such as if it would make sense to allow for a binding assignment in a nested expression.  This may not make sense and maybe it should throw an exceptino if attempted.

e.g.
```clj

(defrule my-rule
  [MyType1 (= ?x x)]
  [MyType2 (or (= ?x y)
               (= ?y y))] ; Doesn't make sense?

  =>
  (println "doesn't matter"))

**Comment by mrrodriguez** [comment]
I suppose another alternative is to just wrap nested expressions in a function and call that in a non-nested way. 
Still a little awkward. Especially for cases like 'or'.

**Comment by rbrush** [comment]
Agreed this is something we should support. He current behavior is probably
an accident of how the binding operation works. I'll poke around this a bit
and see what's going on here

**Comment by rbrush** [comment]
Fixed this by supporting nested bind expressions if the variable in that bind expression is bound previously. This satisfies the use case for the original item Mike logged. 

If the a nested bind is used for a variable not bound elsewhere, we throw an exception when compiling the rule. Consider this example originally posted by Mike:

```clj
(defrule my-rule
  [MyType1 (= ?x x)]
  [MyType2 (or (= ?x y)
               (= ?y y))] ; Doesn't make sense?

  =>
  (println "doesn't matter"))
```

It's not clear what ?y should be. Therefore we do not support this type of expression, with ?y not previously bound, and throw a descriptive exception saying why this is invalid.

**Comment by mrrodriguez** [comment]
+1 
to getting these working.

I have logged a related follow-up @ https://github.com/rbrush/clara-rules/issues/97.

However, I do not think this is a "regression" introduced from these changes.  I haven't checked explicitly, but this issue is a "subset" of the next issue I'd think.
