### ISSUE TITLE
Allow reference of queries by name rather than value

### ISSUE THREAD

**Issue by levand** [rbrush/clara-rules#93]
Currently, the `clara.rules/query` function requires that users pass the entire query object, which must be equal to the one that was compiled into the session to start with.

This isn't a problem when using rules defined with `defquery` - just use the defined var. But it can become cumbersome when using production sources other than namespaces.

It should be possible to pass just the *name* of a query to query, and have it look up the query itself from the compiled session.

**Comment by rbrush** [comment]
Looks like this is a bug in the ClojureScript port...I had actually done exactly this in the Clojure version. I should have time later today to port it over. 

I can't wait for feature expressions so I can drop the duplication that led to the difference. ;)

**Comment by rbrush** [comment]
Actually, I think this is already in place for ClojureScript as well. For defrule, the rule name is a string that is the namspace-qualified var name, but of course other rule sources could provide arbitrary names.

In any case, I adjusted a test locally and ran the below, which worked. Of course, If there is some use case that isn't yielding the expected results I can take a look.

```clj
(deftest test-simple-join

  (let [session (-> my-session
                    (insert (->Temperature 15 "MCI"))
                    (insert (->WindSpeed 45 "MCI"))
                    (fire-rules))]

    (.log js/console "Query name:" (:name wind-without-temperature))
    (is (= #{{:?w 45 :?t 15 :?loc "MCI"}}
           (set
            (query session "clara.test-rules/wind-with-temperature"))))))
```

**Comment by levand** [comment]
Ah - it appears it does work. Sorry! Looks like I had a typo, and then misread the code.

**Comment by rbrush** [comment]
Been there, done that! No worries.
